version: "3.8"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-net

  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    depends_on:
      - mysql-db
    ports:
      - "9090:9090"  # app runs on 9090 as defined in application-dev.properties
    environment:
      SPRING_PROFILES_ACTIVE: dev-doc
      APP_USER_EMAIL: your-email@gmail.com
      APP_USER_PASSWORD: your-app-password
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/TODO_DB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
    networks:
      - todo-net

volumes:
  mysql_data:

networks:
  todo-net:
